In [20]:
# Hide deprecation warnings
import warnings
warnings.filterwarnings('ignore')

# Common imports
import numpy as np
import pandas as pd
import seaborn as sns



# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# To format floats
from IPython.display import display
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [3]:
!ls

Untitled.ipynb          training_set_labels.csv
test_set_values.csv     training_set_values.csv

In [7]:
output = pd.read_csv('training_set_labels.csv')
df = pd.read_csv('training_set_values.csv')

In [9]:
df.head().T

,0,1,2,3,4
id,69572,8776,34310,67743,19728
amount_tsh,6000,0,25,0,0
date_recorded,2011-03-14,2013-03-06,2013-02-25,2013-01-28,2011-07-13
funder,Roman,Grumeti,Lottery Club,Unicef,Action In A
gps_height,1390,1399,686,263,0
installer,Roman,GRUMETI,World vision,UNICEF,Artisan
longitude,34.9381,34.6988,37.4607,38.4862,31.1308
latitude,-9.85632,-2.14747,-3.82133,-11.1553,-1.82536
wpt_name,none,Zahanati,Kwa Mahundi,Zahanati Ya Nanyumbu,Shuleni
num_private,0,0,0,0,0
basin,Lake Nyasa,Lake Victoria,Pangani,Ruvuma / Southern Coast,Lake Victoria
subvillage,Mnyusi B,Nyamara,Majengo,Mahakamani,Kyanyamisa
region,Iringa,Mara,Manyara,Mtwara,Kagera
region_code,11,20,21,90,18
district_code,5,2,4,63,1
lga,Ludewa,Serengeti,Simanjiro,Nanyumbu,Karagwe
ward,Mundindi,Natta,Ngorika,Nanyumbu,Nyakasimbi
population,109,280,250,58,0
public_meeting,True,NaN,True,True,True
recorded_by,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd
scheme_management,VWC,Other,VWC,VWC,NaN
scheme_name,Roman,NaN,Nyumba ya mungu pipe scheme,NaN,NaN
permit,False,True,True,True,True
construction_year,1999,2010,2009,1986,0
extraction_type,gravity,gravity,gravity,submersible,gravity
extraction_type_group,gravity,gravity,gravity,submersible,gravity
extraction_type_class,gravity,gravity,gravity,submersible,gravity
management,vwc,wug,vwc,vwc,other
management_group,user-group,user-group,user-group,user-group,other
payment,pay annually,never pay,pay per bucket,never pay,never pay
payment_type,annually,never pay,per bucket,never pay,never pay
water_quality,soft,soft,soft,soft,soft
quality_group,good,good,good,good,good
quantity,enough,insufficient,enough,dry,seasonal
quantity_group,enough,insufficient,enough,dry,seasonal
source,spring,rainwater harvesting,dam,machine dbh,rainwater harvesting
source_type,spring,rainwater harvesting,dam,borehole,rainwater harvesting
source_class,groundwater,surface,surface,groundwater,surface
waterpoint_type,communal standpipe,communal standpipe,communal standpipe multiple,communal standpipe multiple,communal standpipe
waterpoint_type_group,communal standpipe,communal standpipe,communal standpipe,communal standpipe,communal standpipe

In [10]:
df.region

0               Iringa
1                 Mara
2              Manyara
3               Mtwara
4               Kagera
5                Tanga
6            Shinyanga
7            Shinyanga
8               Tabora
9               Kagera
10               Pwani
11              Ruvuma
12           Shinyanga
13         Kilimanjaro
14           Shinyanga
15               Rukwa
16              Iringa
17              Iringa
18              Mwanza
19              Iringa
20              Iringa
21           Shinyanga
22              Iringa
23         Kilimanjaro
24              Kigoma
25         Kilimanjaro
26               Lindi
27              Kagera
28         Kilimanjaro
29         Kilimanjaro
             ...
59370           Kigoma
59371        Shinyanga
59372           Tabora
59373            Rukwa
59374        Shinyanga
59375            Tanga
59376          Singida
59377           Tabora
59378           Iringa
59379           Kagera
59380           Iringa
59381            Tanga
59382      Kilimanjaro
59383            Lindi
59384           Kagera
59385             Mara
59386            Rukwa
59387    Dar es Salaam
59388           Kigoma
59389            Rukwa
59390            Rukwa
59391      Kilimanjaro
59392            Mbeya
59393           Tabora
59394         Morogoro
59395      Kilimanjaro
59396           Iringa
59397            Mbeya
59398           Dodoma
59399         Morogoro
Name: region, Length: 59400, dtype: object

In [15]:
pd.get_dummies(df.region)

,Arusha,Dar es Salaam,Dodoma,Iringa,Kagera,Kigoma,Kilimanjaro,Lindi,Manyara,Mara,...,Morogoro,Mtwara,Mwanza,Pwani,Rukwa,Ruvuma,Shinyanga,Singida,Tabora,Tanga
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
19,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59370,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59371,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59372,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59373,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
59375,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
59376,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
59377,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59378,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59379,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59380,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
59382,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59383,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
59384,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59385,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
59386,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59387,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59388,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59389,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
59391,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59392,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59394,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
59395,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59396,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59398,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59399,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [17]:
df.head().T

,0,1,2,3,4
id,69572,8776,34310,67743,19728
amount_tsh,6000,0,25,0,0
date_recorded,2011-03-14,2013-03-06,2013-02-25,2013-01-28,2011-07-13
funder,Roman,Grumeti,Lottery Club,Unicef,Action In A
gps_height,1390,1399,686,263,0
installer,Roman,GRUMETI,World vision,UNICEF,Artisan
longitude,34.9381,34.6988,37.4607,38.4862,31.1308
latitude,-9.85632,-2.14747,-3.82133,-11.1553,-1.82536
wpt_name,none,Zahanati,Kwa Mahundi,Zahanati Ya Nanyumbu,Shuleni
num_private,0,0,0,0,0
basin,Lake Nyasa,Lake Victoria,Pangani,Ruvuma / Southern Coast,Lake Victoria
subvillage,Mnyusi B,Nyamara,Majengo,Mahakamani,Kyanyamisa
region,Iringa,Mara,Manyara,Mtwara,Kagera
region_code,11,20,21,90,18
district_code,5,2,4,63,1
lga,Ludewa,Serengeti,Simanjiro,Nanyumbu,Karagwe
ward,Mundindi,Natta,Ngorika,Nanyumbu,Nyakasimbi
population,109,280,250,58,0
public_meeting,True,NaN,True,True,True
recorded_by,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd
scheme_management,VWC,Other,VWC,VWC,NaN
scheme_name,Roman,NaN,Nyumba ya mungu pipe scheme,NaN,NaN
permit,False,True,True,True,True
construction_year,1999,2010,2009,1986,0
extraction_type,gravity,gravity,gravity,submersible,gravity
extraction_type_group,gravity,gravity,gravity,submersible,gravity
extraction_type_class,gravity,gravity,gravity,submersible,gravity
management,vwc,wug,vwc,vwc,other
management_group,user-group,user-group,user-group,user-group,other
payment,pay annually,never pay,pay per bucket,never pay,never pay
payment_type,annually,never pay,per bucket,never pay,never pay
water_quality,soft,soft,soft,soft,soft
quality_group,good,good,good,good,good
quantity,enough,insufficient,enough,dry,seasonal
quantity_group,enough,insufficient,enough,dry,seasonal
source,spring,rainwater harvesting,dam,machine dbh,rainwater harvesting
source_type,spring,rainwater harvesting,dam,borehole,rainwater harvesting
source_class,groundwater,surface,surface,groundwater,surface
waterpoint_type,communal standpipe,communal standpipe,communal standpipe multiple,communal standpipe multiple,communal standpipe
waterpoint_type_group,communal standpipe,communal standpipe,communal standpipe,communal standpipe,communal standpipe

In [33]:
ten_biggest = df.funder.value_counts()[:9].index

In [38]:
def f(x):
    if x.funder in ten_biggest:
        return x.funder
    else:
        return 'other'

In [40]:
df.funder = df.apply(f, axis=1)

In [41]:
df.funder

0                         other
1                         other
2                         other
3                        Unicef
4                         other
5                         other
6                         other
7                         Rwssp
8                         other
9                         other
10                        other
11                       Danida
12                 World Vision
13                        other
14                        other
15                        other
16                       Unicef
17                       Unicef
18                       Hesawa
19                       Danida
20                        other
21                        other
22                       Unicef
23                        other
24                        other
25       Government Of Tanzania
26                        other
27                       Hesawa
28       Government Of Tanzania
29                        other
                  ...
59370                     other
59371                     other
59372                     other
59373                     other
59374                     Rwssp
59375    Government Of Tanzania
59376                     other
59377    Government Of Tanzania
59378                     other
59379                     other
59380                     other
59381                     other
59382                     other
59383                World Bank
59384                     other
59385                     other
59386                     other
59387                     other
59388                     other
59389                     other
59390                     other
59391    Government Of Tanzania
59392    Government Of Tanzania
59393                     other
59394                World Bank
59395                     other
59396                     other
59397                     other
59398                     other
59399                World Bank
Name: funder, Length: 59400, dtype: object

In [42]:
df = pd.get_dummies(df, columns = categorical)

,id,amount_tsh,date_recorded,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,...,funder_Danida,funder_Government Of Tanzania,funder_Hesawa,funder_Kkkt,funder_Rwssp,funder_Tasaf,funder_Unicef,funder_World Bank,funder_World Vision,funder_other
0,69572,6000.00000,2011-03-14,1390,Roman,34.93809,-9.85632,none,0,Lake Nyasa,...,0,0,0,0,0,0,0,0,0,1
1,8776,0.00000,2013-03-06,1399,GRUMETI,34.69877,-2.14747,Zahanati,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
2,34310,25.00000,2013-02-25,686,World vision,37.46066,-3.82133,Kwa Mahundi,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
3,67743,0.00000,2013-01-28,263,UNICEF,38.48616,-11.15530,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,...,0,0,0,0,0,0,1,0,0,0
4,19728,0.00000,2011-07-13,0,Artisan,31.13085,-1.82536,Shuleni,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
5,9944,20.00000,2011-03-13,0,DWE,39.17280,-4.76559,Tajiri,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
6,19816,0.00000,2012-10-01,0,DWSP,33.36241,-3.76636,Kwa Ngomho,0,Internal,...,0,0,0,0,0,0,0,0,0,1
7,54551,0.00000,2012-10-09,0,DWE,32.62062,-4.22620,Tushirikiane,0,Lake Tanganyika,...,0,0,0,0,1,0,0,0,0,0
8,53934,0.00000,2012-11-03,0,Water Aid,32.71110,-5.14671,Kwa Ramadhan Musa,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
9,46144,0.00000,2011-08-03,0,Artisan,30.62699,-1.25705,Kwapeto,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
10,49056,0.00000,2011-02-20,62,Private,39.20952,-7.03414,Mzee Hokororo,0,Wami / Ruvu,...,0,0,0,0,0,0,0,0,0,1
11,50409,200.00000,2013-02-18,1062,DANIDA,35.77026,-10.57417,Kwa Alid Nchimbi,0,Lake Nyasa,...,1,0,0,0,0,0,0,0,0,0
12,36957,0.00000,2012-10-14,0,World vision,33.79811,-3.29019,Pamba,0,Internal,...,0,0,0,0,0,0,0,0,1,0
13,50495,0.00000,2013-03-15,1368,Lawatefuka water sup,37.09257,-3.18178,Kwa John Izack Mmari,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
14,53752,0.00000,2012-10-20,0,WEDECO,34.36407,-3.62933,Mwabasabi,0,Internal,...,0,0,0,0,0,0,0,0,0,1
15,61848,0.00000,2011-08-04,1645,DWE,31.44412,-8.27496,Kwa Juvenal Ching'Ombe,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
16,48451,500.00000,2011-07-04,1703,DWE,34.64244,-9.10618,Kwa John Mtenzi,0,Rufiji,...,0,0,0,0,0,0,1,0,0,0
17,58155,0.00000,2011-09-04,1656,DWE,34.56927,-9.08551,Kwa Rose Chaula,0,Rufiji,...,0,0,0,0,0,0,1,0,0,0
18,34169,0.00000,2011-07-22,1162,DWE,32.92015,-1.94787,Ngomee,0,Lake Victoria,...,0,0,1,0,0,0,0,0,0,0
19,18274,500.00000,2011-02-22,1763,Danid,34.50897,-9.89441,none,0,Lake Nyasa,...,1,0,0,0,0,0,0,0,0,0
20,48375,200.00000,2011-02-27,2216,TWE,34.47343,-9.59499,none,0,Lake Nyasa,...,0,0,0,0,0,0,0,0,0,1
21,6091,0.00000,2013-02-10,0,DWE,0.00000,-0.00000,Muungano,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
22,58500,0.00000,2011-10-04,1510,DWE,34.58690,-8.98001,Shuleni,0,Rufiji,...,0,0,0,0,0,0,1,0,0,0
23,37862,500.00000,2013-11-03,672,ISF,37.94003,-4.12559,Kinonga,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
24,51058,0.00000,2013-01-21,1645,DWE,29.74707,-4.49557,Kamsasa,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
25,22308,0.00000,2013-02-25,1273,DWE,37.42275,-3.31754,Kwa Tukai,0,Pangani,...,0,1,0,0,0,0,0,0,0,0
26,55012,500.00000,2013-01-16,200,Kilolo Star,39.37078,-9.94253,Ruhoma Primary School,0,Ruvuma / Southern Coast,...,0,0,0,0,0,0,0,0,0,1
27,20145,0.00000,2011-07-11,0,DWE,31.10426,-1.73536,Kwawilliam,0,Lake Victoria,...,0,0,1,0,0,0,0,0,0,0
28,19685,0.00000,2013-03-05,1443,District council,37.61113,-3.26353,Kwa Kibakaya,0,Pangani,...,0,1,0,0,0,0,0,0,0,0
29,69124,0.00000,2013-03-16,1256,Lawatefuka water sup,37.06169,-3.19199,Kwa Willium Kinda,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59370,14796,200.00000,2013-01-29,1154,NaN,30.05873,-4.90263,Village Office,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
59371,20387,0.00000,2012-10-09,0,DWE,33.58641,-3.04037,Ushirika,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
59372,29940,0.00000,2012-10-31,0,TLC,32.05855,-5.05210,Kwa Mzee Kamanya,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
59373,15233,5000.00000,2013-01-30,1137,Distri,32.12502,-6.78436,Kwa Kadiega,0,Lake Rukwa,...,0,0,0,0,0,0,0,0,0,1
59374,49651,0.00000,2012-10-29,0,DWE,0.00000,-0.00000,Nguvu Kazi,0,Lake Victoria,...,0,0,0,0,1,0,0,0,0,0
59375,50998,40000.00000,2011-08-03,54,DWE,39.04694,-5.06149,Sekondari,0,Pangani,...,0,1,0,0,0,0,0,0,0,0
59376,34716,0.00000,2013-02-03,1581,NaN,34.82104,-5.07626,Nasingo,0,Internal,...,0,0,0,0,0,0,0,0,0,1
59377,43986,0.00000,2012-10-23,0,Government,33.43701,-4.42359,Fpct,0,Internal,...,0,1,0,0,0,0,0,0,0,0
59378,38067,500.00000,2011-03-21,2101,ACRA,34.62039,-9.35840,Michael Msigwa,0,Rufiji,...,0,0,0,0,0,0,0,0,0,1
59379,58255,0.00000,2011-07-13,0,DO,31.61328,-1.82023,Coffee Plantati,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
59380,30647,6000.00000,2011-03-14,1439,Roman,34.94210,-9.84920,none,0,Lake Nyasa,...,0,0,0,0,0,0,0,0,0,1
59381,67885,0.00000,2011-03-16,0,DWE,38.83500,-4.88020,Mijohoroni,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
59382,47002,6.00000,2013-08-03,1383,DWE,37.45476,-3.32360,Kwa Luka Msaki,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
59383,44616,0.00000,2013-01-19,11,World bank,39.62601,-10.05750,Shuleni,0,Ruvuma / Southern Coast,...,0,0,0,0,0,0,0,1,0,0
59384,72148,0.00000,2011-07-10,0,CONCERN,30.66780,-2.48371,Chamkube,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
59385,34473,500.00000,2012-11-03,1327,JAICA CO,33.95168,-2.02185,Kwa Marunda,0,Lake Victoria,...,0,0,0,0,0,0,0,0,0,1
59386,34952,0.00000,2011-08-22,1786,DWE,31.73879,-8.53201,Shule Ya Sekondari Katazi,0,Lake Rukwa,...,0,0,0,0,0,0,0,0,0,1
59387,26640,100.00000,2013-03-12,25,0,39.17648,-6.95710,Kwa Maliba,0,Wami / Ruvu,...,0,0,0,0,0,0,0,0,0,1
59388,72559,0.00000,2013-01-29,1414,DWE,30.69240,-3.59383,Kwa Philipo Kibeba,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
59389,30410,0.00000,2011-08-06,783,DWE,30.64649,-7.36542,Sekondari,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
59390,13677,0.00000,2011-08-04,1715,DWE,31.37085,-8.25816,Kwa Mzee Atanas,0,Lake Tanganyika,...,0,0,0,0,0,0,0,0,0,1
59391,44885,0.00000,2013-08-03,540,Government,38.04407,-4.27222,Kwa,0,Pangani,...,0,1,0,0,0,0,0,0,0,0
59392,40607,0.00000,2011-04-15,0,Government,33.00944,-8.52089,Benard Charles,0,Lake Rukwa,...,0,1,0,0,0,0,0,0,0,0
59393,48348,0.00000,2012-10-27,0,Private,33.86685,-4.28741,Kwa Peter,0,Internal,...,0,0,0,0,0,0,0,0,0,1
59394,11164,500.00000,2011-03-09,351,ML appro,37.63405,-6.12483,Chimeredya,0,Wami / Ruvu,...,0,0,0,0,0,0,0,1,0,0
59395,60739,10.00000,2013-05-03,1210,CES,37.16981,-3.25385,Area Three Namba 27,0,Pangani,...,0,0,0,0,0,0,0,0,0,1
59396,27263,4700.00000,2011-05-07,1212,Cefa,35.24999,-9.07063,Kwa Yahona Kuvala,0,Rufiji,...,0,0,0,0,0,0,0,0,0,1
59397,37057,0.00000,2011-04-11,0,NaN,34.01709,-8.75043,Mashine,0,Rufiji,...,0,0,0,0,0,0,0,0,0,1
59398,31282,0.00000,2011-03-08,0,Musa,35.86132,-6.37857,Mshoro,0,Rufiji,...,0,0,0,0,0,0,0,0,0,1
59399,26348,0.00000,2011-03-23,191,World,38.10405,-6.74746,Kwa Mzee Lugawa,0,Wami / Ruvu,...,0,0,0,0,0,0,0,1,0,0

In [146]:
df.dtypes[df.dtypes == object].index.values

array(['date_recorded', 'funder', 'installer', 'wpt_name', 'basin',
       'subvillage', 'region', 'lga', 'ward', 'public_meeting',
       'recorded_by', 'scheme_management', 'scheme_name', 'permit',
       'construction_year', 'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group',
       'payment', 'payment_type', 'water_quality', 'quality_group',
       'quantity', 'quantity_group', 'source', 'source_type',
       'source_class', 'waterpoint_type', 'waterpoint_type_group'], dtype=object)

In [45]:
df.source_type.value_counts()

spring                  17021
shallow well            16824
borehole                11949
river/lake              10377
rainwater harvesting     2295
dam                       656
other                     278
Name: source_type, dtype: int64

In [49]:
df.source.value_counts()['river'] + df.source.value_counts()['lake']

10377

In [47]:
df.source_class.value_counts()

groundwater    45794
surface        13328
unknown          278
Name: source_class, dtype: int64

In [50]:
df.installer.value_counts()

DWE                        17402
Government                  1825
RWE                         1206
Commu                       1060
DANIDA                      1050
KKKT                         898
Hesawa                       840
0                            777
TCRS                         707
Central government           622
CES                          610
Community                    553
DANID                        552
District Council             551
HESAWA                       539
World vision                 408
LGA                          408
WEDECO                       397
TASAF                        396
District council             392
Gover                        383
AMREF                        329
TWESA                        316
WU                           301
Dmdd                         287
ACRA                         278
World Vision                 270
SEMA                         249
DW                           246
OXFAM                        234
                           ...
Pump entecostal Sweeden        1
Perusi Bhoke                   1
Emmanuel kitaponda             1
Localtechnician                1
MAISHULE                       1
Chacha Issame                  1
OLOMOLOKI                      1
Government/TCRS                1
College                        1
USA EMBASSY                    1
HAIDOMU LUTHERAN CHURCH        1
Water user Group               1
KAGERA MINE                    1
FRANKFURT                      1
Grumeti fund                   1
NJOONJOO                       1
Kiwanda cha Ngozi              1
Seff Mtambo                    1
Bonite Bottles Ltd             1
Goldwill  foundation           1
British                        1
Villages                       1
Mketo                          1
DANIAD                         1
chacha                         1
VIFAI                          1
Anglica Church                 1
Tanza                          1
Anglikan                       1
DADS/village Community         1
Name: installer, Length: 2145, dtype: int64

In [51]:
len(df.installer.unique())

2146

In [60]:
df[df.construction_year == 0].shape

(20709, 40)

In [55]:
df.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

In [61]:
from sklearn.preprocessing import Imputer

In [62]:
df.shape

(59400, 40)

In [63]:
df.construction_year

0        1999
1        2010
2        2009
3        1986
4           0
5        2009
6           0
7           0
8           0
9           0
10       2011
11       1987
12          0
13       2009
14          0
15       1991
16       1978
17       1978
18       1999
19       1992
20       2008
21          0
22       1978
23       2011
24       2009
25       1974
26       2011
27          0
28       2000
29       2002
         ...
59370       0
59371       0
59372       0
59373    1988
59374       0
59375    2005
59376    1990
59377       0
59378    2008
59379       0
59380    1999
59381    1992
59382    2008
59383    2008
59384       0
59385    2011
59386    2009
59387    2000
59388    1995
59389    2009
59390    1991
59391    1967
59392       0
59393       0
59394    2007
59395    1999
59396    1996
59397       0
59398       0
59399    2002
Name: construction_year, Length: 59400, dtype: int64

In [68]:
df.construction_year.astype(str).str.len().value_counts()

4    38691
1    20709
Name: construction_year, dtype: int64

In [85]:
df.construction_year.astype(str).str[2:3] +'0s'
def g(x):
    if x['construction_year'] == '0s':
        return 'unknown'
    
df.construction_year = df.apply(g, axis = 1)

In [86]:
df.construction_year

0        None
1        None
2        None
3        None
4        None
5        None
6        None
7        None
8        None
9        None
10       None
11       None
12       None
13       None
14       None
15       None
16       None
17       None
18       None
19       None
20       None
21       None
22       None
23       None
24       None
25       None
26       None
27       None
28       None
29       None
         ...
59370    None
59371    None
59372    None
59373    None
59374    None
59375    None
59376    None
59377    None
59378    None
59379    None
59380    None
59381    None
59382    None
59383    None
59384    None
59385    None
59386    None
59387    None
59388    None
59389    None
59390    None
59391    None
59392    None
59393    None
59394    None
59395    None
59396    None
59397    None
59398    None
59399    None
Name: construction_year, Length: 59400, dtype: object

In [87]:
df.gps_height

0        1390
1        1399
2         686
3         263
4           0
5           0
6           0
7           0
8           0
9           0
10         62
11       1062
12          0
13       1368
14          0
15       1645
16       1703
17       1656
18       1162
19       1763
20       2216
21          0
22       1510
23        672
24       1645
25       1273
26        200
27          0
28       1443
29       1256
         ...
59370    1154
59371       0
59372       0
59373    1137
59374       0
59375      54
59376    1581
59377       0
59378    2101
59379       0
59380    1439
59381       0
59382    1383
59383      11
59384       0
59385    1327
59386    1786
59387      25
59388    1414
59389     783
59390    1715
59391     540
59392       0
59393       0
59394     351
59395    1210
59396    1212
59397       0
59398       0
59399     191
Name: gps_height, Length: 59400, dtype: int64

In [88]:
imp = Imputer(missing_values=0, strategy='mean')

In [94]:
imp.fit_transform(df[['longitude', 'latitude']], y='gps_height')

array([[ 34.93809275,  -9.85632177],
       [ 34.6987661 ,  -2.14746569],
       [ 37.46066446,  -3.82132853],
       ...,
       [ 34.01708706,  -8.75043433],
       [ 35.86131531,  -6.37857327],
       [ 38.10404822,  -6.74746425]])

In [95]:
df[['longitude', 'latitude']]

       longitude  latitude
0       34.93809  -9.85632
1       34.69877  -2.14747
2       37.46066  -3.82133
3       38.48616 -11.15530
4       31.13085  -1.82536
5       39.17280  -4.76559
6       33.36241  -3.76636
7       32.62062  -4.22620
8       32.71110  -5.14671
9       30.62699  -1.25705
10      39.20952  -7.03414
11      35.77026 -10.57417
12      33.79811  -3.29019
13      37.09257  -3.18178
14      34.36407  -3.62933
15      31.44412  -8.27496
16      34.64244  -9.10618
17      34.56927  -9.08551
18      32.92015  -1.94787
19      34.50897  -9.89441
20      34.47343  -9.59499
21       0.00000  -0.00000
22      34.58690  -8.98001
23      37.94003  -4.12559
24      29.74707  -4.49557
25      37.42275  -3.31754
26      39.37078  -9.94253
27      31.10426  -1.73536
28      37.61113  -3.26353
29      37.06169  -3.19199
...          ...       ...
59370   30.05873  -4.90263
59371   33.58641  -3.04037
59372   32.05855  -5.05210
59373   32.12502  -6.78436
59374    0.00000  -0.00000
59375   39.04694  -5.06149
59376   34.82104  -5.07626
59377   33.43701  -4.42359
59378   34.62039  -9.35840
59379   31.61328  -1.82023
59380   34.94210  -9.84920
59381   38.83500  -4.88020
59382   37.45476  -3.32360
59383   39.62601 -10.05750
59384   30.66780  -2.48371
59385   33.95168  -2.02185
59386   31.73879  -8.53201
59387   39.17648  -6.95710
59388   30.69240  -3.59383
59389   30.64649  -7.36542
59390   31.37085  -8.25816
59391   38.04407  -4.27222
59392   33.00944  -8.52089
59393   33.86685  -4.28741
59394   37.63405  -6.12483
59395   37.16981  -3.25385
59396   35.24999  -9.07063
59397   34.01709  -8.75043
59398   35.86132  -6.37857
59399   38.10405  -6.74746

[59400 rows x 2 columns]

In [93]:
imp.transform(df[['longitude', 'latitude']])

array([[ 34.93809275,  -9.85632177],
       [ 34.6987661 ,  -2.14746569],
       [ 37.46066446,  -3.82132853],
       ...,
       [ 34.01708706,  -8.75043433],
       [ 35.86131531,  -6.37857327],
       [ 38.10404822,  -6.74746425]])

In [104]:
X = df[df[['longitude', 'latitude']].isnull().index]
y = df.gps_height

KeyError: "Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,\n                9,\n            ...\n            59390, 59391, 59392, 59393, 59394, 59395, 59396, 59397, 59398,\n            59399],\n           dtype='int64', length=59400) not in index"

In [105]:
X

RangeIndex(start=0, stop=59400, step=1)

In [107]:
df[['longitude', 'latitude']].isnull()

       longitude  latitude
0          False     False
1          False     False
2          False     False
3          False     False
4          False     False
5          False     False
6          False     False
7          False     False
8          False     False
9          False     False
10         False     False
11         False     False
12         False     False
13         False     False
14         False     False
15         False     False
16         False     False
17         False     False
18         False     False
19         False     False
20         False     False
21         False     False
22         False     False
23         False     False
24         False     False
25         False     False
26         False     False
27         False     False
28         False     False
29         False     False
...          ...       ...
59370      False     False
59371      False     False
59372      False     False
59373      False     False
59374      False     False
59375      False     False
59376      False     False
59377      False     False
59378      False     False
59379      False     False
59380      False     False
59381      False     False
59382      False     False
59383      False     False
59384      False     False
59385      False     False
59386      False     False
59387      False     False
59388      False     False
59389      False     False
59390      False     False
59391      False     False
59392      False     False
59393      False     False
59394      False     False
59395      False     False
59396      False     False
59397      False     False
59398      False     False
59399      False     False

[59400 rows x 2 columns]

In [108]:
df[(df.longitude.isnull()) | (df.latitude.isnull())]

Empty DataFrame
Columns: [id, amount_tsh, date_recorded, funder, gps_height, installer, longitude, latitude, wpt_name, num_private, basin, subvillage, region, region_code, district_code, lga, ward, population, public_meeting, recorded_by, scheme_management, scheme_name, permit, construction_year, extraction_type, extraction_type_group, extraction_type_class, management, management_group, payment, payment_type, water_quality, quality_group, quantity, quantity_group, source, source_type, source_class, waterpoint_type, waterpoint_type_group]
Index: []

[0 rows x 40 columns]

In [115]:
df[df.gps_height != 0].index

Int64Index([    0,     1,     2,     3,    10,    11,    13,    15,    16,
               17,
            ...
            59386, 59387, 59388, 59389, 59390, 59391, 59394, 59395, 59396,
            59399],
           dtype='int64', length=38962)

In [123]:
from sklearn.linear_model import LinearRegression

y_train = df[df.gps_height != 0].gps_height
X_train = df[df.gps_height !=0][['longitude', 'latitude']]
X_test = df[df.gps_height == 0][['longitude', 'latitude']]

model = LinearRegression()
model.fit(X_train, y_train)
y_test = model.predict(X_test)

df.loc[df[df.gps_height == 0].index, 'gps_height'] = y_test

array([ 1818.61745224,   668.11365742,  1454.64659191, ...,  1369.10110663,
        1172.41123001,  1029.63722705])

In [124]:
y_test

array([ 1818.61745224,   668.11365742,  1454.64659191, ...,  1369.10110663,
        1172.41123001,  1029.63722705])

In [127]:
print(len(y_test))
print(len(df[df.gps_height == 0].gps_height))

20438
20438

In [135]:
df[df.gps_height == 0]

Empty DataFrame
Columns: [id, amount_tsh, date_recorded, funder, gps_height, installer, longitude, latitude, wpt_name, num_private, basin, subvillage, region, region_code, district_code, lga, ward, population, public_meeting, recorded_by, scheme_management, scheme_name, permit, construction_year, extraction_type, extraction_type_group, extraction_type_class, management, management_group, payment, payment_type, water_quality, quality_group, quantity, quantity_group, source, source_type, source_class, waterpoint_type, waterpoint_type_group]
Index: []

[0 rows x 40 columns]

In [139]:
df[df.gps_height == 1390].gps_height = 200

In [140]:
df[df.gps_height == 1390]

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.00000,2011-03-14,other,1390.00000,Roman,34.93809,-9.85632,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
2687,51464,0.00000,2013-02-24,other,1390.00000,Kiliwater,37.61137,-3.21998,Kwa Fransis Moshiro,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
6144,58368,0.00000,2012-10-31,Hesawa,1390.00000,DWE,34.02094,-1.93276,Kwa Mangi,0,...,on failure,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
7387,41486,0.00000,2013-02-10,Government Of Tanzania,1390.00000,Community,30.70442,-3.56353,Kwaluhaga,0,...,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring
7718,46579,500.00000,2011-03-29,Unicef,1390.00000,DWE,34.63284,-8.85080,Kwa Peter Nyodiki,0,...,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
9244,45061,20.00000,2013-02-21,other,1390.00000,NaN,35.07876,-4.83685,Shabani,0,...,per bucket,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump
11714,19577,0.00000,2012-10-29,Hesawa,1390.00000,Hesawa,34.50894,-1.96051,Omahe,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
12065,61166,0.00000,2013-03-26,other,1390.00000,Losaa-Kia water supp,37.12473,-3.20421,Kwa Phanael Kileo,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
14194,5343,500.00000,2013-02-27,Danida,1390.00000,DANIDA,34.94604,-10.95251,Kwa Mzee Kimosola,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
19572,7697,0.00000,2013-03-20,Government Of Tanzania,1390.00000,Government,37.96791,-4.44306,Msasa Primary,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
22134,63416,300.00000,2013-02-26,other,1390.00000,CES,37.20072,-3.21480,Kwa Saliandumi Lema,0,...,other,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
23541,54027,0.00000,2013-03-15,other,1390.00000,Lawatefuka water sup,37.08785,-3.16019,Kwa Wilfred Urio,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
25201,43646,0.00000,2013-03-21,other,1390.00000,DWE,37.37509,-3.25527,Kwa Raymond Fokus,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
26519,59748,0.00000,2013-03-20,other,1390.00000,Magadini-Makiwaru wa,36.97122,-3.14558,Kwa Miseyeki Lobukek,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
26990,71744,0.00000,2011-03-08,Tasaf,1390.00000,TASAF,36.02731,-7.60450,none,0,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
30042,34667,0.00000,2013-01-24,Hesawa,1390.00000,Hesawa,34.36299,-1.79916,Charles Wambura,0,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
30757,37386,500.00000,2012-10-19,other,1390.00000,Grobal resource alliance,34.26812,-1.20306,Rambo,0,...,monthly,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
38965,65434,0.00000,2011-03-10,other,1390.00000,Go,36.86055,-6.26323,Shuleni,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
40070,32314,0.00000,2013-02-04,other,1390.00000,DWE,30.82393,-3.03664,Abelrunyagu,0,...,unknown,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
40447,45572,500.00000,2011-03-28,other,1390.00000,wananchi,34.63632,-8.82786,Kwa Mpepwa,0,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
40808,49647,250.00000,2013-02-14,other,1390.00000,OXFAM,30.14809,-4.32963,Kajana Primary,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
42872,62728,0.00000,2011-03-14,other,1390.00000,Roman,34.93900,-9.85432,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
44936,53220,0.00000,2013-03-25,Government Of Tanzania,1390.00000,DWE,37.51596,-3.28512,Kwa Onesmo Moshi,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,other,other
51277,50800,300.00000,2013-03-05,other,1390.00000,District Council,37.65786,-3.67780,Kwa Zaniya,0,...,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
51335,44643,0.00000,2013-03-30,Government Of Tanzania,1390.00000,Government,37.55524,-3.29079,Kwa Ndetandio Temu,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
51959,14889,0.00000,2012-11-02,Hesawa,1390.00000,DWE,34.02309,-1.89871,Kwa Shingisha,0,...,unknown,soft,good,enough,enough,shallow well,shallow well,groundwater,other,other

In [ ]:
|